Clockwork.StreamingSwitcher.Web/Controllers/TidalUserFavoritesController.cs
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Clockwork.StreamingSwitcher.Web.Controllers
{
    public class TidalUserFavoritesController : BaseTidalController
    {
        [Authorize]
        public async Task<ActionResult> Artists()
        {
            return await ViewWithDataOrEmptyResult("Artists", session => session.GetFavoriteArtists());
        }

        [Authorize]
        public async Task<ActionResult> Albums()
        {
            return await ViewWithDataOrEmptyResult("Albums", session => session.GetFavoriteAlbums());
        }

        [Authorize]
        public async Task<ActionResult> Tracks()
        {
            return await ViewWithDataOrEmptyResult("Tracks", session => session.GetFavoriteTracks());
        }

        [Authorize]
        public async Task<ActionResult> Playlists()
        {
            return await ViewWithDataOrEmptyResult("Playlists", session => session.GetFavoritePlaylists());
        }
    }
}

Clockwork.StreamingSwitcher.Web/Controllers/TidalUserPlaylistsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Clockwork.StreamingSwitcher.Web.Models.Tidal;
using Clockwork.StreamingSwitcher.TidalIntegration;

namespace Clockwork.StreamingSwitcher.Web.Controllers
{
    public class TidalUserPlaylistsController : BaseTidalController
    {
        [Authorize]
        public async Task<ActionResult> Index()
        {
            return await ViewWithDataOrEmptyResult("Index", session => session.GetUserPlaylists());
        }

        [Authorize]
        public async Task<ActionResult> Playlist(string playlistUuId)
        {
            var session = await OpenTidlIntegrator.RestoreSessionFromClaimsIdentity(User.Identity);

            if (session == null)
                return new EmptyResult();

            var playlist = await session.GetPlaylist(playlistUuId);

            if (playlist == null)
                return new EmptyResult();

            var tracks = await session.GetPlaylistTracks(playlistUuId);

            var playlistViewModel = new PlaylistViewModel
            {
                Playlist = playlist,
                Tracks = tracks
            };

            return View("Playlist", playlistViewModel);
        }
    }
}

Clockwork.StreamingSwitcher.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/ClientSide/CSS/Site.css" />
    <link rel="stylesheet" href="/ClientSide/CSS/Tidal.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
    @RenderSection("css", required: false)
    <title>@ViewBag.Title - Music Streaming Service Switcher</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Music Streaming Service Switcher", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*TODO Improve dropdown menu*@
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Tidal
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li>@Html.ActionLink("Playlists", "Index", "TidalUserPlaylists")</li>
                                <li>@Html.ActionLink("Fav Artists", "Artists", "TidalUserFavorites")</li>
                                <li>@Html.ActionLink("Fav Albums", "Albums", "TidalUserFavorites")</li>
                                <li>@Html.ActionLink("Fav Tracks", "Tracks", "TidalUserFavorites")</li>
                                <li>@Html.ActionLink("Fav Playlists", "Playlists", "TidalUserFavorites")</li>
                                @*<li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>*@
                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Spotify
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <li>TODO</li>
                            </ul>
                        </div>
                    </li>
                </ul>
                @Html.Partial("Partials/TidalLogin")
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Music Streaming Service Switcher</p>
    </footer>
</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>